# Spectral

### Example matrices

In [5]:
import numpy as np
from walkg.linalg import Spectral

A = np.array([[0.3, 0.4, 0.3],[0.1, 0.8, 0.1],[0.2, 0.6, 0.2]])
H = np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0]])

### Instantiating

In [7]:
# Object of a non-hermitian matrix
a = Spectral(A)

# Object of a hermitian matrix
h = Spectral(H)

In [13]:
print(a)

Spectral(
    Hermitian: False
    Spectra:       1.00,  0.30, -0.00
    Multiplicity:   1  ,   1  ,   1  
)


In [14]:
print(h)

Spectral(
    Hermitian: True
    Spectra:       2.00, -1.00
    Multiplicity:   1  ,   2  
)


### Eigenvectors and Eigenvalues

In [43]:
h.evals

array([ 2., -1.])

In [44]:
h.evcts

array([[-0.57735027,  0.42250331,  0.69868277],
       [-0.57735027, -0.81632869,  0.01655721],
       [-0.57735027,  0.39382538, -0.71523999]])

### Spectrum

In [11]:
a.get_spectra()

(array([ 1.00000000e+00,  3.00000000e-01, -9.20632095e-18]),
 array([1, 1, 1], dtype=int64))

In [12]:
h.get_spectra()

(array([ 2., -1.]), array([1, 2], dtype=int64))

### Eigenspaces

In [15]:
a.get_eigspace(1)

array([[0.57735027],
       [0.57735027],
       [0.57735027]])

In [20]:
h.get_eigspace(1)

array([[-0.57735027],
       [-0.57735027],
       [-0.57735027]])

In [21]:
h.get_eigspace(2)

array([[ 0.42250331,  0.69868277],
       [-0.81632869,  0.01655721],
       [ 0.39382538, -0.71523999]])

### Orthogonal Projectors

In [37]:
h.get_eigproj(1)

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [28]:
h.get_eigproj(2)

array([[ 0.66666667, -0.33333333, -0.33333333],
       [-0.33333333,  0.66666667, -0.33333333],
       [-0.33333333, -0.33333333,  0.66666667]])