# Spectral

### Example matrices

In [1]:
import numpy as np
from walkg.linalg import Spectral

A = np.array([[0.3, 0.4, 0.3],[0.1, 0.8, 0.1],[0.2, 0.6, 0.2]])
H = np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0]])

### Instantiating

In [2]:
# Object of a non-hermitian matrix
a = Spectral(A)

# Object of a hermitian matrix
h = Spectral(H)

In [3]:
print(a)

Spectral(
    Hermitian: False
    Spectra:       1.00,  0.30, -0.00
    Multiplicity:   1  ,   1  ,   1  
)


In [4]:
print(h)

Spectral(
    Hermitian: True
    Spectra:       2.00, -1.00
    Multiplicity:   1  ,   2  
)


### Eigenvectors and Eigenvalues

In [5]:
h.evals

array([ 2., -1.])

In [6]:
h.evcts

array([[-0.57735027,  0.42250331,  0.69868277],
       [-0.57735027, -0.81632869,  0.01655721],
       [-0.57735027,  0.39382538, -0.71523999]])

### Spectrum

In [7]:
a.get_spectra()

(array([ 1.00000000e+00,  3.00000000e-01, -9.20632095e-18]),
 array([1, 1, 1], dtype=int64))

In [8]:
h.get_spectra()

(array([ 2., -1.]), array([1, 2], dtype=int64))

### Eigenspaces

In [9]:
a.get_eigspace(1)

array([[0.57735027],
       [0.57735027],
       [0.57735027]])

In [10]:
h.get_eigspace(1)

array([[-0.57735027],
       [-0.57735027],
       [-0.57735027]])

In [11]:
h.get_eigspace(2)

array([[ 0.42250331,  0.69868277],
       [-0.81632869,  0.01655721],
       [ 0.39382538, -0.71523999]])

### Orthogonal Projectors

In [12]:
h.get_eigproj(1)

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [13]:
h.get_eigproj(2)

array([[ 0.66666667, -0.33333333, -0.33333333],
       [-0.33333333,  0.66666667, -0.33333333],
       [-0.33333333, -0.33333333,  0.66666667]])

### Schur products

In [14]:
h.get_eigschur(1,2)

array([[ 0.22222222, -0.11111111, -0.11111111],
       [-0.11111111,  0.22222222, -0.11111111],
       [-0.11111111, -0.11111111,  0.22222222]])

In [15]:
h.get_eigschur(2)

array([[0.44444444, 0.11111111, 0.11111111],
       [0.11111111, 0.44444444, 0.11111111],
       [0.11111111, 0.11111111, 0.44444444]])

### Applying a function

In [25]:
a.act_eigfun(np.exp)

array([[1.42872821, 0.86082541, 0.42872821],
       [0.195489  , 2.32730382, 0.195489  ],
       [0.31210861, 1.09406462, 1.31210861]])

In [26]:
h.act_eigfun(lambda x: np.exp(x*1j))

array([[ 0.22148593-0.25788151j, -0.31881638+0.58358947j,
        -0.31881638+0.58358947j],
       [-0.31881638+0.58358947j,  0.22148593-0.25788151j,
        -0.31881638+0.58358947j],
       [-0.31881638+0.58358947j, -0.31881638+0.58358947j,
         0.22148593-0.25788151j]])